version: "3.9"
services:
  app:
    build:
      context: .
      target: runtime
    env_file: .env
    volumes:
      - logs:/app/notebooks/logs
    ports:
      - "8868:8868"
    depends_on:
      sqlserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8868"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - energieapp-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD:-YourStrong!Passw0rd}", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - energieapp-net

volumes:
  logs:
  sqlserver-data:

networks:
  energieapp-net:
    driver: bridge
