version: "3.9"

services:
  energieapp:
    container_name: energieapp

    # ① Try to pull; ② build locally when --build is given (launcher adds it)
    image: svb966/energieapp:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REV: dev        # optional label for local builds

    working_dir: /opt/app
    ports:
      - "127.0.0.1:${PORT:-8868}:${PORT:-8868}"
    environment:
      - PORT=${PORT:-8868}
    volumes:
      - "./logs:/opt/app/logs"

    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 $$PORT || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3

    restart: unless-stopped
